"""Reports for the three analyzers: Markdown for people, CSV for trackers, JSON for automation."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Sequence

from secopt import __version__
from secopt.core.model import Opportunity, money, total_saving
from secopt.core.output import md_inline, md_table, to_json, write_csv, write_text
from secopt.licenses.analyze import LicenseReport
from secopt.overlap.analyze import OverlapReport
from secopt.overlap.capabilities import DOMAINS
from secopt.sentinel.analyze import SentinelReport

OPPORTUNITY_FIELDS = ("area", "id", "title", "monthly_saving", "additive", "effort", "detail", "action")
FOOTER = f"Generated by cloud-security-optimization {__version__}. Read-only: nothing was changed."


def _amount(o: Opportunity, currency: str) -> str:
    if o.monthly_saving is None:
        return "-"
    return money(o.monthly_saving, currency) + ("" if o.additive else " *")


def _opportunities_md(opportunities: Sequence[Opportunity], currency: str) -> list[str]:
    lines = ["## Opportunities", ""]
    if not opportunities:
        return lines + ["Nothing found. 🎉", ""]
    saving = total_saving(opportunities)
    overlapping = [o for o in opportunities if o.monthly_saving is not None and not o.additive]
    if saving:
        lines += [f"**Estimated saving: up to {money(saving, currency)} a month "
                  f"({money(saving * 12, currency)} a year).**", ""]
    lines.append(md_table(["#", "Opportunity", "Saving / month", "Effort"],
                          [(n, o.title, _amount(o, currency), o.effort) for n, o in enumerate(opportunities, start=1)]))
    lines.append("")
    if overlapping:
        lines += ["\\* Estimated at today's effective price per GB. These overlap with each other and with a "
                  "pricing-plan change, so they are not included in the total and should not be added up.", ""]
    for n, o in enumerate(opportunities, start=1):
        lines += [f"### {n}. {md_inline(o.title)}", "", md_inline(o.detail), "",
                  f"**What to do:** {md_inline(o.action)}", ""]
    return lines


def _notes_md(notes: Sequence[str]) -> list[str]:
    if not notes:
        return []
    return ["## Notes", ""] + [f"- {md_inline(note)}" for note in notes] + [""]


def _pct(value: float | None) -> str:
    if value is None:
        return "-"
    return "0%" if round(value) == 0 else f"{value:+.0f}%"


def sentinel_markdown(report: SentinelReport, source: str, captured: str) -> str:
    t, cur = report.totals, report.totals["currency"]
    summary = [("Billable ingestion, Analytics plan", f"{t['gb_per_day']:,.1f} GB/day (peak {t['peak_gb_per_day']:,.1f})")]
    if t.get("basic_gb_per_day"):
        summary.append(("Billable ingestion, Basic plan", f"{t['basic_gb_per_day']:,.1f} GB/day"))
    if t.get("other_plan_gb_per_day"):
        summary.append(("Ingestion on other plans (not priced)", f"{t['other_plan_gb_per_day']:,.1f} GB/day"))
    summary += [
        ("Free ingestion in the period", f"{t['free_gb']:,.0f} GB"),
        ("Pricing plan", t["current_plan"]),
        ("Estimated cost", f"{money(t['monthly_cost'], cur)} a month" if t["monthly_cost"] is not None else "n/a"),
        ("Effective price, Analytics plan", f"{money(t['effective_price_per_gb'], cur)} per GB"
         if t["effective_price_per_gb"] else "n/a"),
        ("Tables with billable data", t["tables_with_billable_data"]),
        ("Daily cap", f"{t['daily_cap_gb']} GB" if t["daily_cap_gb"] else "none")]
    lines = ["# Microsoft Sentinel cost review", "",
             f"**Workspace:** {md_inline(t['workspace'])} ({md_inline(t['region'])}) · **Period:** "
             f"{md_inline(t['first_day'])} to {md_inline(t['last_day'])} ({t['days_analysed']} days) · "
             f"**Captured:** {md_inline(captured)} · **Source:** {md_inline(source)}", "", "## Summary", "",
             md_table(["Measure", "Value"], summary), ""]
    lines += _opportunities_md(report.opportunities, cur)
    if report.pricing_options:
        lines += ["## Pricing plans compared", "",
                  "Monthly cost of the Analytics-plan ingestion you actually had, under each plan. "
                  "Only Analytics-plan data counts toward a commitment tier.", "",
                  md_table(["Plan", "Cost / month", ""], [
                      (o["plan"], money(o["monthly_cost"], cur), "current" if o["current"] else "")
                      for o in report.pricing_options if o["tier_gb"] is None or o["current"]
                      or o["tier_gb"] <= max(100, 4 * t["gb_per_day"])]), ""]
    lines += ["## Tables", "",
              md_table(["Table", "GB/day", "Share", "Cost / month", "Plan", "Retention", "Rules", "7-day trend"], [
                  (r["table"], f"{r['gb_per_day']:,.2f}", f"{r['share_pct']:.1f}%",
                   money(r["monthly_cost"], cur) if r["monthly_cost"] is not None else "-", r["plan"],
                   f"{r['retention_days']} d" if r["retention_days"] else "-",
                   "-" if r["rules"] is None else r["rules"], _pct(r["trend_pct"]))
                  for r in report.tables if r["billable_gb"] > 0]), "",
              "_Rules = enabled analytics rules whose query names the table. Free tables are not listed._", ""]
    lines += _notes_md(report.notes) + ["---", FOOTER]
    return "\n".join(lines)


def licenses_markdown(report: LicenseReport, source: str, captured: str) -> str:
    t, cur = report.totals, report.totals["currency"]
    lines = ["# Microsoft 365 licence review", "",
             f"**Captured:** {md_inline(captured)} · **Source:** {md_inline(source)}", "", "## Summary", "",
             md_table(["Measure", "Value"], [
                 ("Paid products", t["paid_products"]),
                 ("Licensed users", "n/a" if t["licensed_users"] is None else t["licensed_users"]),
                 ("Unassigned licences", t["unassigned"]),
                 ("On disabled accounts", t["on_disabled_accounts"]),
                 (f"On accounts with no sign-in for {t['inactive_days']} days", t["on_inactive_accounts"]),
                 ("Duplicated by a suite", t["duplicates"]),
                 ("Estimated waste", f"{money(t['monthly_waste'], cur)} a month" if t["monthly_waste"] is not None
                  else "n/a (no price given for these products)")]), ""]
    lines += _opportunities_md(report.opportunities, cur)
    lines += ["## Products", "",
              md_table(["Product", "Purchased", "Assigned", "Unassigned", "Disabled", "Inactive", "Duplicate",
                        "Price", "Waste / month"], [
                  (p["product"], p["purchased"], p["assigned"], p["unassigned"], p["disabled"], p["inactive"],
                   p["duplicate"], money(p["price"], cur) if p["price"] is not None else "-",
                   money(p["monthly_waste"], cur) if p["monthly_waste"] is not None else "-")
                  for p in report.products if not p["free"]]), ""]
    lines += _notes_md(report.notes) + ["---", FOOTER]
    return "\n".join(lines)


def overlap_markdown(report: OverlapReport, source: str) -> str:
    t, cur = report.totals, report.totals["currency"]
    lines = ["# Security tool overlap review", "", f"**Source:** {md_inline(source)}", "", "## Summary", "",
             md_table(["Measure", "Value"], [
                 ("Tools", f"{t['tools']} ({t['paid_tools']} paid separately)"),
                 ("Annual spend", money(t["annual_spend"], cur)),
                 ("Capabilities covered", t["capabilities_covered"]),
                 ("Capabilities provided by more than one tool", t["capabilities_overlapping"]),
                 ("Required capabilities with no tool", t["gaps"]),
                 ("Spend on fully redundant tools", f"{money(t['redundant_annual_spend'], cur)} a year "
                                                    f"({t['redundant_pct']:.0f}% of spend)")]), ""]
    lines += _opportunities_md(report.opportunities, cur)
    lines += ["## Capability matrix", "", "**Gap** = required, but no tool in the inventory provides it.", ""]
    for domain in DOMAINS:
        rows = [r for r in report.matrix if r["domain"] == domain]
        if not rows:
            continue
        lines += [f"### {domain}", "",
                  md_table(["Capability", "Provided by", "Status"], [
                      (r["name"], ", ".join(r["tools"]) or "-",
                       {"gap": "**Gap**", "overlap": f"Overlap ({len(r['tools'])})", "covered": "Covered"}[r["status"]])
                      for r in rows]), ""]
    lines += ["## Tools", "",
              md_table(["Tool", "Vendor", "Cost / year", "Only this tool provides", "Also provided elsewhere"], [
                  (r["tool"], r["vendor"] or "-",
                   money(r["annual_cost"], cur) if r["annual_cost"] else f"bundled ({r['bundled_with'] or 'no separate cost'})",
                   ", ".join(r["unique"]) or "nothing", ", ".join(r["shared"]) or "-") for r in report.tools]), ""]
    lines += _notes_md(report.notes) + ["---", FOOTER]
    return "\n".join(lines)


def write_reports(out_dir: Path, stem: str, formats: Sequence[str], markdown: str, payload: dict[str, Any],
                  opportunities: Sequence[Opportunity], detail_rows: Sequence[dict[str, Any]],
                  detail_fields: Sequence[str], detail_name: str) -> list[Path]:
    written: list[Path] = []
    if "md" in formats:
        path = out_dir / f"{stem}.md"
        write_text(path, markdown)
        written.append(path)
    if "csv" in formats:
        path = out_dir / f"{stem}-opportunities.csv"
        write_csv(path, [o.to_dict() for o in opportunities], OPPORTUNITY_FIELDS)
        written.append(path)
        path = out_dir / f"{stem}-{detail_name}.csv"
        write_csv(path, detail_rows, detail_fields)
        written.append(path)
    if "json" in formats:
        path = out_dir / f"{stem}.json"
        full = {"tool": "cloud-security-optimization", "version": __version__,
                "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"), **payload,
                "opportunities": [o.to_dict() for o in opportunities],
                "estimated_monthly_saving": total_saving(opportunities)}
        write_text(path, to_json(full))
        written.append(path)
    return written
